default: &default
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSW'] %>

development:
  <<: *default
  database: simple_pages_development

test:
  <<: *default
  database: simple_pages_test

production:
  <<: *default
  database: simple_pages_production
